### ISSUE TITLE
Killswitch status reported incorrectly

### ISSUE THREAD

**Issue by Zeioth** [calexandru2018/linux-gui-legacy#33]
**Describe the bug**
Killswitch status reported incorrectly. Always reported as disabled.

**To Reproduce**
1. run "protonvpn configure"
2. choose 5, and then 1 to enable the killswitch
3. Open protonvpn-tray > show GUI
4. Killswitch will still be reported as disabled

**Expected behavior**
The program reports killswitch enabled/disabled according to protonvpn.

**Screenshots**
![ks](https://user-images.githubusercontent.com/3357792/78795179-fc2b6d00-79b4-11ea-8139-f55eec93c39a.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version: latest

**Comment by calexandru2018** [comment]
Thank you for reporting the issue. I was indeed able to replicate it. I have now fixed this and will be releasing a new update very soon.

Sidenote: I also noticed that when changing killswitch from within the configurations, the dashboard label for the killswitch did not update accordingly. This should also be fixed in the next update.
