### ISSUE TITLE
Protonvpn-tray can't spawn protonvpn-gui

### ISSUE THREAD

**Issue by Zeioth** [calexandru2018/linux-gui-legacy#34]
**Describe the bug**
When you open protonvpn-tray, everything works correctly. But after some minutes  protonvpn-tray is unable to spawn proton-gui. Most likely this happens when the sudo permissions expire.

**To Reproduce**
1. Add protonvpn to the autorun folder.
2. Wait 30 minutes
3. Click on the tray icon, and then "show GUI" -> Nothing happens
4. Run "sudo pkill protonvpn-tray && protonvpn-tray"
5. Now protonvpn-tray is able to spawn protonvpn-gui again, after being asked for sudo password trough console..

**Expected behavior**
I see two options here:
1. Keep protonvpn running on background always, so the sudo permissions are remembered.
or
2. Use visudo to asks for sudo password.

**Desktop (please complete the following information):**
 - OS: Manjaro XFCE
 - Version: Latest

**Comment by calexandru2018** [comment]
Interesting, did you add protonvpn-gui to the visudo file ?
Can you do anything else such as quick connect or disconnect ?
Edit: Have you tested doing the same within the space of 5min or 10min ? 

I was trying to replicate the issue but without success atm. I will try to make some more tests to be sure that I have not missed something.

**Comment by Zeioth** [comment]
I've tried again. It seems I was wrong after booting the machine it doesn't work. I'll edit this comment in an hour to re-check the sudo timeout issue.

https://www.youtube.com/watch?v=WDAqchrkeNo&feature=youtu.be

EDIT: Yes, I can confirm the sudo timeout problem too.

![timeout](https://user-images.githubusercontent.com/3357792/78816788-7c140000-79d2-11ea-9375-76b6c2660e4b.png)

So there's two issues here:
1. When you open protonvpn-tray on startup, it won't have permissions to open protonvpn-gui.
2. Even if you manually open protonvpn-tray and enter your sudo password, once you close the protonvpn GUI window, you will lost sudo permissions in about 10 minutes (which means that, again, protonvpn-tray won't be able to open protonvpn-gui unless you re-introduce the sudo password)

**Comment by calexandru2018** [comment]
Alright I get a better picture now, thank you!

As it is at the moment, this is somehow expected since the tray and the GUI work independently from each other. To be able to call the GUI from the tray, you would need [to add protonvpn-gui to the visudo file](https://github.com/calexandru2018/protonvpn-linux-gui#visudosudoless), and only then it should work without any problems. The point with adding the GUI to the visudo file is so that it does not prompt the user for the sudo password each time you will want to call it, thus improving UX.

I might take a look into it in the near future so that it prompts the user for the sudo password, so I'll mark this as a low prio enhancement.

**Comment by scottAnselmo** [comment]
Minor nitpick, but given:

> 1. When you open protonvpn-tray on startup, it won't have permissions to open protonvpn-gui.

It might be best to re-title issue to "Protonvpn-tray can't spawn protonvpn-gui" since 2. is a derivative symptom of 1.

**Comment by calexandru2018** [comment]
This issue is now solved if user enables PolKit from within the GUI, #67
