### ISSUE TITLE
Not working on Manjaro KDE (Manual Installation)

### ISSUE THREAD

**Issue by SuperITMan** [calexandru2018/linux-gui-legacy#40]
Hello,

First at all, thanks for your work and sharing :+1: 
It seems to be a really nice application. Unfortunately, for an unknown reason, I'm not able to use it on my Manjaro KDE :disappointed: 

**Describe the bug**

Cannot use the application because it tries to read the file "~/.pvpn-gui/pvpn-gui.cfg" which does not exist in my current configuration.

It returns the following error: 

```bash
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/protonvpn_linux_gui_calexandru2018-2.0.2-py3.8.egg/protonvpn_linux_gui/thread_functions.py", line 72, in load_content_on_start
    return_value = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/protonvpn_linux_gui_calexandru2018-2.0.2-py3.8.egg/protonvpn_linux_gui/utils.py", line 338, in load_on_start
    display_secure_core = get_gui_config("connections", "display_secure_core")
  File "/usr/lib/python3.8/site-packages/protonvpn_linux_gui_calexandru2018-2.0.2-py3.8.egg/protonvpn_linux_gui/utils.py", line 60, in get_gui_config
    return config[group][key]
  File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'connections'
```

What did I do:
```bash
sudo python3 setup.py install
sudo protonvpn-gui
```

**Screenshots**
Result: 
![image](https://user-images.githubusercontent.com/10333565/79438167-b7aa5d80-7fc2-11ea-996a-4895fc6fb23b.png)

And when the error happens, the following window appears behind the other one:
![image](https://user-images.githubusercontent.com/10333565/79441890-5769ea80-7fc7-11ea-828b-654fc24ad1ec.png)

**Desktop (please complete the following information):**
 - OS: `uname -r` -> "5.4.31-1-MANJARO" 
 - Version: 2.0.2 (master)

**Additional context**
protonvpn-cli is already installed and configured. It's working well. Maybe a conflict with protonvpn-gui ?

Thanks for your help! :blush:

**Comment by calexandru2018** [comment]
Thank you for the report @SuperITMan ! 
This issue is due to that the profile was initialized via CLI and not the GUI, thus it can not find an intialized GUI configuration. **I will definitely fix this in a upcoming update**, in the meantime to solve this issue, create a `pvpn-gui.cfg` file inside the `~/.pvpn-gui/` with the following content:

[connections]
display_secure_core = False

[general_tab]
start_min = False
start_on_boot = False
show_notifications = False

[tray_tab]
display_data_tx = 0
display_server = 0
display_time_conn = 0
display_serverload = 0

[conn_tab]
autoconnect = dis
quick_connect = dis

**Comment by SuperITMan** [comment]
Hi @calexandru2018 ! 
Thanks for the quick answer.

Before applying this, I removed the "~/.pvpn-cli" folder and tried to run the application.
I guess the dark theme is not supported yet. :stuck_out_tongue: 
![image](https://user-images.githubusercontent.com/10333565/79459910-8d1ccc80-7fe3-11ea-9b0c-f1d63f1aa4ff.png)

Nevertheless, I'm able to connect with my openvpn protonmail credentials :blush: 
![image](https://user-images.githubusercontent.com/10333565/79460072-d240fe80-7fe3-11ea-9821-73cbcb46289f.png)

I think we could a section in the TroubleShooting section with information about the file to add. And also explain that we can simply remove the protonvpn config for now :blush: 
I can create a PR for this if you prefer.

Regards,
Alexis

**Comment by calexandru2018** [comment]
@SuperITMan Great, glad to hear that you fixed it by yourself.
Actually in the release notes of V2 I recommended users first to purge their CLI configurations and re-install the GUI to avoid any issue.

The new fix is on the way! Another thing that I noticed from your screens is the color/theme issues. I'm trying to fix these so that I can later push the update.

Edit: About the dark mode, yeah I am working on it. Some themes such as Adwaita kinda of forces certain styles on certain elements. A temporary solution will soon be provided! :)
