### ISSUE TITLE
GUI not launching in Debian Buster Gnome Wayland

### ISSUE THREAD

**Issue by thediamondgeezer** [calexandru2018/linux-gui-legacy#44]
**Describe the bug**
GUI doesn't launch when command is executed.

**To Reproduce**
user@home:~$ sudo protonvpn-gui
[sudo] password for user: 
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused

(protonvpn-gui:2698): Gtk-CRITICAL **: 11:33:37.292: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(protonvpn-gui:2698): Gtk-CRITICAL **: 11:33:37.292: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(protonvpn-gui:2698): Gtk-CRITICAL **: 11:33:37.292: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault
user@home:

**Expected behavior**
GUI launches.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Browser N/A
- Version Debian 10

**Additional context**
I've installed as per instructions (protonvpn-cli already present).

**Comment by calexandru2018** [comment]
@thediamondgeezer thank you for posting the issue. If you don't mind, please edit your post so that it follows the predefined "Issue Temaplate", it'll make it easier for me to understand it.

Now, I have been able to replicate this issue. And it is indeed due to Wayland ~~though this issue is two-folded~~

~~The first part is `No protocol specified Unable to init server: Could not connect: Connection refused No protocol specified Unable to init server: Could not connect: Connection refused` and that is related directly for it not being enabled in Wayland mode. To solve that, GTK has instructions on how the software should be launched, `sudo GDK_BACKEND=wayland protonvpn-gui`.~~

~~The second part is regarding the Gtk-Critical message,~~ I will still look into this, but it has something to with root and Wayland.
Edit(@thediamondgeezer): So as I suspected, this issue is due that Wayland [does not allow GUIs to be started as root](https://wiki.debian.org/Wayland#Xwayland). Since many of the actions are needed to manage configurations and also access protonvpns cli configurations, root access is needed. I managed to test this on a Debian Buster. I removed most of the root necessary code (for debugging purposes) and launched the GUI with only `protonvpn-gui` and it worked.

![Screenshot from 2020-04-18 13-47-04](https://user-images.githubusercontent.com/31934100/79637109-02b3a480-816c-11ea-873a-540804d29d7a.png)

So for the GUI to work, it needs to be launched as a normal user and all root necessary actions should prompt the user for root password, [quote from debian page](https://wiki.debian.org/Wayland#Xwayland):

> There are plans to allow X11 applications running as root to use XWayland but native Wayland applications need to be restructured into a GUI part and a root part. 

I will definitely attempt to solve this issue though it will require some good amount of code refactoring, so this might take a while to get fixed.

**WORKAROUND**
Edit2: Well, I actually managed to get around it. There is something called [x11-xserver-utils](https://packages.debian.org/sid/x11-xserver-utils) and this allows you to [bypass Waylands sudo restriction](https://wiki.archlinux.org/index.php/Running_GUI_applications_as_root#Using_xhost), more info [here](https://beamtic.com/sudo-and-guis). Bear in mind that this is more of a hack then a solution at the moment.
![Screenshot from 2020-04-18 14-24-07](https://user-images.githubusercontent.com/31934100/79637512-ace0fb80-816f-11ea-8f39-446f3604dd79.png)

**Comment by thediamondgeezer** [comment]
I've just updated to 2.0.6 and I can't run the command without root. When I run as root, I still get the error, and the GUI does not launch:

----------------------------------------

user@home:~$ protonvpn-gui
[sudo] password for user: 
[!] The program was not executed as root.
[!] Please run as root.
user@home:~$ sudo !!
sudo protonvpn-gui
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused

(protonvpn-gui:3272): Gtk-CRITICAL **: 16:37:01.352: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(protonvpn-gui:3272): Gtk-CRITICAL **: 16:37:01.352: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(protonvpn-gui:3272): Gtk-CRITICAL **: 16:37:01.352: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault

----------------------------------------

**Comment by calexandru2018** [comment]
@thediamondgeezer This issue will take a while to get fixed, since all commands run through root to acess all CLI configurations, such as  username and password which are root protected, etc. So you will still have to use the workaround for now, until it gets a more permanent fix.

**Comment by scottAnselmo** [comment]
This doesn't seem to be limited to Wayland, or Debian. Get similar issues for X11 on EndeavourOS (Arch) on Plasma when installed via AUR (haven't tested pip).

**Issues:**

1. Clicking "ProtonVPN GUI" from Application Launcher fails to launch GUI. "ProtonVPN GUI Tray" from Application Launcher however does launch an icon into systray
2. Right clicking systray and doing QuickConnect (or Disconnect if connected) results in no state changes. "Show GUI" also does nothing. "Quit" however does remove systray icon. Worth noting systray can read state and update icon (i.e. will turn green if I run `sudo protonvpn c -f`)
3. Clicking X (Close) in Dashboard does not minimize to systray

**Workaround to launch GUI:**

Run `sudo protonvpn-linux-gui`. Quick connect, etc in GUI initializes connection w/o issue.

**System Info:**
Operating System: Arch Linux 
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel Version: 5.6.13-arch1-1
OS Type: 64-bit

**Comment by calexandru2018** [comment]
Hi @sanecito

Please do read the documentation and also any previously created issues, as what you are describing has already posted by previous users (see #55 and #34), and the solution for that is [here](https://github.com/ProtonVPN/linux-gui#visudosudoless).

What you are experiencing is not the same issue as described by @thediamondgeezer . If it had been the same then you would even not be able to run with `sudo protonvpn-gui`, since Wayland blocks all GUI applications from being run as `sudo`.

**Comment by scottAnselmo** [comment]
Thanks for highlighting, was operating off symptom description for issue relevancy ("GUI not launching" vs "Protonvpn-tray can't spawn protonvpn-gui **after some minutes**")

**Comment by calexandru2018** [comment]
Hello @thediamondgeezer :)
I just wanted to let you know that the next update will fix the sudo issue for Wayland, so you will not need to utilize the previous hack to make it work.

Whenever you get the chance to try out the new version, don't forget to do `xhost -si:localuser:root`.

**Comment by thediamondgeezer** [comment]
Thanks for letting me know, I'm looking forward to it :-)
Regards

Jerome

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
