### ISSUE TITLE
Application based Exception in Split Tunneling

### ISSUE THREAD

**Issue by redpinko1917** [calexandru2018/linux-gui-legacy#53]
**Is your feature request related to a problem? Please describe.**
Media server is made very inefficient when being routed through VPN. There's no way to keep track of all the IP's I need to add exceptions for.

**Describe the solution you'd like**
A function like that of the official windows client wherein you can exclude based on the application is exactly what we need

**Describe alternatives you've considered**
I've instead utilized a VM for p2p stuff but this greatly draws on resources

Thank you!

**Comment by calexandru2018** [comment]
Hi @redpinko1917  , 
I am myself interested in finding a way to do this tbh. I have found some sources that point to the use of namespaces. Though the real main "issue" here is that the rules are all created and written by the CLI, and a new namespace needs to be created before applying the rules created by the CLI, so this kind of creates a chicken/egg situation. Nonetheless, I will look into it and see how this could be achieved. Worst case scenario would be to wait until the CLI releases that feature.

**Comment by calexandru2018** [comment]
Hi @redpinko1917 :)

This is something that will be worked on in the future, although it will firstly be implemented via the CLI. Since the the GUI works on top of the CLI, there is no point in working on such a feature only for the GUI.

I will be closing this issue, feel free to comment or send me an email! :)
