### ISSUE TITLE
PolicyKit support

### ISSUE THREAD

**Issue by t1meshift** [calexandru2018/linux-gui-legacy#55]
**Is your feature request related to a problem? Please describe.**
In my opinion, the GUI does not need running as root all the time, it should escalate its privileges only when the app actually needs that. Moreover, `sudo` can't be run without tty after timeout without `visudo` configuration, which is quite inconvenient. Also my issue is a bit related with #34 :)

**Describe the solution you'd like**
Since the majority of running Linux distributions has PolicyKit running out of the box, the GUI could use it, e.g. when connecting. For those who couldn't use PolicyKit for whatever reason, it could degrade gracefully to the current behavior with a warning message.

**Describe alternatives you've considered**
`gksudo` could be used for that, but the main issue is that running a GUI app as root is too unsafe.

**Comment by calexandru2018** [comment]
Hi @t1meshift , thank you for your suggestion! :)

About this issue, tbh I was a bit unsure if a should close it or not since as you have written, this is related to #34 , but also to #44 in some way. But, since other users might point out the same issue, I might as well leave this one for now to avoid any future confusions or issues related to this one.

About the topic itself, yeah I do agree about that the GUI should not be launched with sudo, and there is definitely an improvement to be done here. I'll be definitely working on to improve on that aspect.

**Comment by calexandru2018** [comment]
This has now been implemented, #67
