### ISSUE TITLE
The github web page does not tell the user to install the linux-cli BEFORE installing the GUI.

### ISSUE THREAD

**Issue by Chummpp** [calexandru2018/linux-gui-legacy#74]
**Describe the bug**
After manuall installation the terminal came back with what you see bellow.
 Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from protonvpn_linux_gui.constants import VERSION
  File "/home/dennis/linux-gui/protonvpn_linux_gui/constants.py", line 2, in <module>
    from protonvpn_cli.constants import VERSION as cli_version, USER as cli_user
ModuleNotFoundError: No module named 'protonvpn_cli'

**To Reproduce**
1. Type git clone https://github.com/ProtonVPN/linux-gui
2. Type cd linux-gui
3. Type sudo python3 setup.py install

**Expected behavior**
I expected the GUI to load.

**Screenshots**
https://postimg.cc/G8vGrMjN, https://i.postimg.cc/Tw49VF5R/Linux-mint-19-protonvpn-GUI.png

**Desktop (please complete the following information):**
 - OS: [Linux mint 19.3]

**Comment by calexandru2018** [comment]
Hi @Chummpp :)

Thank you for creating this issue. This is indeed something that definitely needs to be fixed, thank you for highlighting it! 

~~The idea here is that when you run `sudo python3 setup.py install`, the CLI should be automatically installed. I will fix this asap!~~

Edit: I will update manual install instructions. Instead of `sudo python3 setup.py install`, first install the CLI (`sudo pip3 install protonvpn-cli`) and then install the GUI, with the following line: `sudo pip3 install -e .`
