### ISSUE TITLE
CLI template update has broken GUI 

### ISSUE THREAD

**Issue by baarkerlounger** [calexandru2018/linux-gui-legacy#79]
**Describe the bug**
No longer possible to install/run this GUI using the latest version of the CLI since they've removed the `make_ovpn_template` method in `utils` and moved to Jinja templates.

**To Reproduce**
Install the ProtonVPN-cli and ProtonVPN-gui via the normal Ubuntu instructions.
Run `protonvpm-gui`:
```
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn-gui", line 5, in <module>
    from protonvpn_linux_gui.gui import initialize_gui
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_linux_gui/gui.py", line 16, in <module>
    from .utils import (
  File "/usr/local/lib/python3.8/dist-packages/protonvpn_linux_gui/utils.py", line 12, in <module>
    from protonvpn_cli.utils import (
ImportError: cannot import name 'make_ovpn_template' from 'protonvpn_cli.utils' (/usr/local/lib/python3.8/dist-packages/protonvpn_cli/utils.py)
```

**Expected behavior**
The GUI launches

**Desktop (please complete the following information):**
Ubuntu 20.04

**Additional context**

**Comment by calexandru2018** [comment]
Hi @baarkerlounger  :)

This has already been previously posted, #72 
A fix for this has been already pushed to the master branch, and an update will be soon pushed to PyPi, until then, if you want to continue using the GUI, either clone the master branch or downgrade to CLI v.2.2.2 with the command specified in the previous issue.

I am closing this issue since it is a duplicate and it has already been resolved. :+1:
